services:
  redis:
    image: redis:7-alpine
    container_name: cp_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solver_api
    restart: unless-stopped
    ports:
      - "${PORT:-8083}:${PORT:-8083}"
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solver_worker
    restart: unless-stopped
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_URL=http://api:8082/capacity-planning/complete
      - PORT = 8083
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
